name =input("Input your Name : ")
nim =input("Input your NIM : ")

print("......................................")
print(". Welcome to",name,                    )
print(". With your NIM",nim,                  )
print("......................................")
print()

print("Question No.1")
print("Diketahui sisi = 6, Sebutkan Nama dan hitunglah Luas Bangun Datar tersebut!")
bd1  = input("Nama Bangun Datar = ")
sisi = eval(input("Sisi : "))
sisi2 = eval(input("Sisi : "))
print("Bangun Datar tersebut adalah",bd1,"dan Luas Bangun Datar Tersebut adalah",(sisi * sisi2))
print()
print()

print("Question No.2")
print("Diketahui alas = 7, tinggi = 8, Sebutkan Nama dan hitunglah Luas Bangun Datar tersebut!")
bd2 = input("Nama Bangun Datar = ")
alas = float(input("Alas : "))
tinggi = float(input("Tinggi : "))
print("Bangun Datar tersebut adalah",bd2,"dan Luas Bangun Datar Tersebut adalah",(alas * tinggi / 2))
print()
print()

print("Question No.3")
print("Diketahui Panjang = 4, Lebar = 9, Sebutkan Nama dan hitunglah Luas Bangun Datar tersebut!")
bd3 = input("Nama Bangun Datar = ")
panjang = eval(input("Panjang : "))
lebar = eval(input("Lebar : "))
print("Bangun Datar tersebut adalah",bd3,"dan Luas Bangun Datar Tersebut adalah",(panjang * lebar))
print()
print()

print("Question No.4")
print("Diketahui Jari-jari = 56, Sebutkan Nama dan hitunglah Luas Bangun Datar tersebut!")
bd4 = input("Nama Bangun Datar = ")
𝝅 = float(input("𝝅 : "))
r = eval(input("r  : "))
print("Bangun Datar tersebut adalah",bd4,"dan Luas Bangun Datar Tersebut adalah",(𝝅 * r * r))
print()
print()

print("Question No.5")
print("Diketahui Diagonal I = 4, Diagonal II = 8, Sebutkan Nama dan hitunglah Luas Bangun Datar tersebut!")
bd5 = input("Nama Bangun Datar = ")
d1 = float(input("Diagonal I :  "))
d2 = eval(input("Diagonal II :  "))
print("Bangun Datar tersebut adalah",bd5,"dan Luas Bangun Datar Tersebut adalah",(d1 * d2 / 2))
print()
print()

print("Question No.6")
print("Diketahui sisi AB dan CD sejajar, sisi AB = 6, sisi CD = 8, tinggi = 3. Sebutkan Nama dan hitunglah Luas Bangun Datar tersebut!")
bd6 = input("Nama Bangun Datar = ")
ab = float(input("Sisi AB : "))
cd = eval(input("Sisi CD : "))
t = eval(input("Tinggi : "))
print("Bangun Datar tersebut adalah",bd6,"dan Luas Bangun Datar Tersebut adalah",((ab+cd) * t / 2))
print()
print()

print("Question No.7")
print("Diketahui alas = 9, tinggi = 7, Sebutkan Nama dan hitunglah Luas Bangun Datar tersebut!")
bd7 = input("Nama Bangun Datar = ")
alas = eval(input("Alas : "))
tinggi = eval(input("Tinggi : "))
print("Bangun Datar tersebut adalah",bd7,"dan Luas Bangun Datar Tersebut adalah",(alas * tinggi))
print()
print()

print("........................................")
print(                                          )
print('"Thank You Very Much For Your Attention"')
print(                                          )
print("........................................")